const IMAGES = {
    icons: {
        afterEffects: require("./icons/AfterEffects.png"),
        aws: require("./icons/AWS.png"),
        bash: require("./icons/Bash.png"),
        bem: require("./icons/BEM.png"),
        bootstrap: require("./icons/Bootstrap.png"),
        css: require("./icons/CSS.png"),
        discord: require("./icons/Discord.svg").default,
        expressJS: require("./icons/ExpressJS.png"),
        figma: require("./icons/Figma.png"),
        git: require("./icons/Git.png"),
        github: require("./icons/Github.png"),
        google: require("./icons/google.png"),
        html: require("./icons/HTML.png"),
        illustrator: require("./icons/Illustrator.png"),
        java: require("./icons/Java.png"),
        javascript: require("./icons/JavaScript.png"),
        jquery: require("./icons/JQuery.png"),
        jsonIcon: require("./icons/json.png"),
        markdown: require("./icons/Markdown.png"),
        mongoDB: require("./icons/MongoDB.png"),
        nodeJS: require("./icons/NodeJS.png"),
        npmIcon: require("./icons/NPMIcon.png"),
        photoshop: require("./icons/Photoshop.png"),
        php: require("./icons/PHP.png"),
        premier: require("./icons/Premier.png"),
        python: require("./icons/Python.png"),
        reactIcon: require("./icons/ReactIcon.png"),
        restAPI: require("./icons/RestAPI.png"),
        sass: require("./icons/Sass.png"),
        stackOverflow: require("./icons/StackOverflow.png"),
        vsCode: require("./icons/VSCode.png"),
        wordpress: require("./icons/Wordpress.png"),
        xd: require("./icons/xd.png"),
        next: require("./icons/NextJS.png"),
        vercel: require("./icons/Vercel.png"),
        tailwind: require("./icons/TailwindCSS.png"),
        typescript: require("./icons/TypeScript.png"),
    },
};

export default IMAGES;
